language: elixir
elixir: 1.7.3
otp_release:
  - 21.2
notifications:
  email:
    - vince@newrelic.com
services:
  - docker
script:
  - docker-compose up -d
  - mix format --check-formatted
  - mix test
  - cd examples/sample_app && mix test
